// ============================================================
// OmniBuilder Component Registry - 60+ production components
// Organized by category for the visual builder
// ============================================================

export interface BNode {
  id: string;
  type: string;
  tag: string;
  content: string;
  styles: Record<string, string>;
  children: BNode[];
  locked?: boolean;
  hidden?: boolean;
  name?: string;
}

function uid(): string {
  return 'n' + Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
}

export interface CompDef {
  name: string;
  nodes: BNode[];
}

export const CATEGORIES: Record<string, CompDef[]> = {
  'Layout': [
    {name:'Section',nodes:[{id:uid(),type:'section',tag:'section',content:'',name:'Section',styles:{padding:'48px 32px'},children:[]}]},
    {name:'Container',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'Container',styles:{padding:'24px',maxWidth:'1200px',margin:'0 auto'},children:[]}]},
    {name:'2 Columns',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'2 Columns',styles:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'24px',padding:'24px'},children:[{id:uid(),type:'container',tag:'div',content:'',name:'Col 1',styles:{padding:'16px',background:'#f9fafb',borderRadius:'8px',minHeight:'120px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',name:'Col 2',styles:{padding:'16px',background:'#f9fafb',borderRadius:'8px',minHeight:'120px'},children:[]}]}]},
    {name:'3 Columns',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'3 Columns',styles:{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'24px',padding:'24px'},children:[{id:uid(),type:'container',tag:'div',content:'',name:'Col 1',styles:{padding:'16px',background:'#f9fafb',borderRadius:'8px',minHeight:'120px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',name:'Col 2',styles:{padding:'16px',background:'#f9fafb',borderRadius:'8px',minHeight:'120px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',name:'Col 3',styles:{padding:'16px',background:'#f9fafb',borderRadius:'8px',minHeight:'120px'},children:[]}]}]},
    {name:'4 Columns',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'4 Columns',styles:{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'16px',padding:'24px'},children:[{id:uid(),type:'container',tag:'div',content:'',styles:{padding:'16px',background:'#f9fafb',borderRadius:'8px',minHeight:'100px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{padding:'16px',background:'#f9fafb',borderRadius:'8px',minHeight:'100px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{padding:'16px',background:'#f9fafb',borderRadius:'8px',minHeight:'100px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{padding:'16px',background:'#f9fafb',borderRadius:'8px',minHeight:'100px'},children:[]}]}]},
    {name:'Sidebar Left',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'Sidebar Layout',styles:{display:'grid',gridTemplateColumns:'240px 1fr',gap:'24px',padding:'24px'},children:[{id:uid(),type:'container',tag:'aside',content:'',name:'Sidebar',styles:{padding:'20px',background:'#f9fafb',borderRadius:'12px'},children:[]},{id:uid(),type:'container',tag:'main',content:'',name:'Main',styles:{padding:'20px',border:'1px solid #e5e7eb',borderRadius:'12px',minHeight:'300px'},children:[]}]}]},
    {name:'Flex Row',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'Flex Row',styles:{display:'flex',gap:'16px',alignItems:'center',padding:'16px'},children:[]}]},
    {name:'Flex Column',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'Flex Column',styles:{display:'flex',flexDirection:'column',gap:'16px',padding:'16px'},children:[]}]},
    {name:'Card',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'Card',styles:{padding:'24px',borderRadius:'16px',border:'1px solid #e5e7eb',background:'#fff',boxShadow:'0 1px 3px rgba(0,0,0,0.1)'},children:[{id:uid(),type:'heading',tag:'h3',content:'Card Title',styles:{fontSize:'1.1rem',fontWeight:'700',marginBottom:'8px'},children:[]},{id:uid(),type:'text',tag:'p',content:'Card description goes here.',styles:{color:'#6b7280',fontSize:'0.9rem'},children:[]}]}]},
    {name:'Panel',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'Panel',styles:{padding:'24px',borderRadius:'12px',background:'#f8fafc',border:'1px solid #e2e8f0'},children:[]}]},
  ],
  'Typography': [
    {name:'H1',nodes:[{id:uid(),type:'heading',tag:'h1',content:'Heading 1',styles:{fontSize:'3rem',fontWeight:'800',letterSpacing:'-0.02em'},children:[]}]},
    {name:'H2',nodes:[{id:uid(),type:'heading',tag:'h2',content:'Heading 2',styles:{fontSize:'2rem',fontWeight:'700'},children:[]}]},
    {name:'H3',nodes:[{id:uid(),type:'heading',tag:'h3',content:'Heading 3',styles:{fontSize:'1.5rem',fontWeight:'700'},children:[]}]},
    {name:'Paragraph',nodes:[{id:uid(),type:'text',tag:'p',content:'Your paragraph text. Click to edit inline.',styles:{color:'#374151',lineHeight:'1.7',fontSize:'1rem'},children:[]}]},
    {name:'Small Text',nodes:[{id:uid(),type:'text',tag:'p',content:'Small supporting text.',styles:{color:'#6b7280',fontSize:'0.875rem'},children:[]}]},
    {name:'Lead Text',nodes:[{id:uid(),type:'text',tag:'p',content:'Lead paragraph with larger font for emphasis.',styles:{fontSize:'1.25rem',color:'#4b5563',lineHeight:'1.6'},children:[]}]},
    {name:'Blockquote',nodes:[{id:uid(),type:'text',tag:'blockquote',content:'This is an important quote that stands out.',styles:{borderLeft:'4px solid #7c3aed',paddingLeft:'16px',fontStyle:'italic',color:'#4b5563',margin:'16px 0'},children:[]}]},
    {name:'List',nodes:[{id:uid(),type:'container',tag:'ul',content:'',name:'List',styles:{paddingLeft:'20px',lineHeight:'2'},children:[{id:uid(),type:'text',tag:'li',content:'First item',styles:{},children:[]},{id:uid(),type:'text',tag:'li',content:'Second item',styles:{},children:[]},{id:uid(),type:'text',tag:'li',content:'Third item',styles:{},children:[]}]}]},
    {name:'Badge',nodes:[{id:uid(),type:'text',tag:'span',content:'NEW',styles:{background:'#7c3aed',color:'#fff',padding:'4px 12px',borderRadius:'20px',fontSize:'0.75rem',fontWeight:'700'},children:[]}]},
    {name:'Code',nodes:[{id:uid(),type:'text',tag:'pre',content:'const greeting = "Hello World";',styles:{background:'#1e293b',color:'#a5f3fc',padding:'16px',borderRadius:'8px',fontSize:'0.85rem',fontFamily:'monospace'},children:[]}]},
  ],
  'Buttons': [
    {name:'Primary Button',nodes:[{id:uid(),type:'button',tag:'button',content:'Get Started',styles:{background:'#7c3aed',color:'#fff',padding:'12px 24px',borderRadius:'8px',fontWeight:'600',border:'none',fontSize:'0.95rem'},children:[]}]},
    {name:'Secondary Button',nodes:[{id:uid(),type:'button',tag:'button',content:'Learn More',styles:{background:'transparent',color:'#7c3aed',padding:'12px 24px',borderRadius:'8px',fontWeight:'600',border:'2px solid #7c3aed'},children:[]}]},
    {name:'Dark Button',nodes:[{id:uid(),type:'button',tag:'button',content:'Continue',styles:{background:'#111827',color:'#fff',padding:'12px 24px',borderRadius:'8px',fontWeight:'600',border:'none'},children:[]}]},
    {name:'Ghost Button',nodes:[{id:uid(),type:'button',tag:'button',content:'Cancel',styles:{background:'transparent',color:'#6b7280',padding:'12px 24px',borderRadius:'8px',fontWeight:'500',border:'1px solid #e5e7eb'},children:[]}]},
    {name:'Pill Button',nodes:[{id:uid(),type:'button',tag:'button',content:'Subscribe',styles:{background:'#7c3aed',color:'#fff',padding:'10px 28px',borderRadius:'999px',fontWeight:'600',border:'none'},children:[]}]},
    {name:'Large CTA',nodes:[{id:uid(),type:'button',tag:'button',content:'Start Free Trial',styles:{background:'linear-gradient(135deg,#7c3aed,#6d28d9)',color:'#fff',padding:'16px 40px',borderRadius:'12px',fontWeight:'700',border:'none',fontSize:'1.1rem',boxShadow:'0 4px 14px rgba(124,58,237,0.3)'},children:[]}]},
  ],
  'Hero': [
    {name:'Hero Centered',nodes:[{id:uid(),type:'section',tag:'section',content:'',name:'Hero Centered',styles:{padding:'80px 32px',textAlign:'center',background:'linear-gradient(135deg,#667eea,#764ba2)'},children:[{id:uid(),type:'heading',tag:'h1',content:'Build Something Amazing',styles:{fontSize:'3.5rem',fontWeight:'800',color:'#fff',marginBottom:'16px'},children:[]},{id:uid(),type:'text',tag:'p',content:'The all-in-one platform for modern teams.',styles:{fontSize:'1.2rem',color:'rgba(255,255,255,0.85)',marginBottom:'32px'},children:[]},{id:uid(),type:'button',tag:'button',content:'Get Started',styles:{background:'#fff',color:'#764ba2',padding:'14px 32px',borderRadius:'8px',fontWeight:'700',border:'none'},children:[]}]}]},
    {name:'Hero Split',nodes:[{id:uid(),type:'section',tag:'section',content:'',name:'Hero Split',styles:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'40px',padding:'80px 48px',alignItems:'center'},children:[{id:uid(),type:'container',tag:'div',content:'',styles:{},children:[{id:uid(),type:'heading',tag:'h1',content:'Design Without Limits',styles:{fontSize:'3rem',fontWeight:'800',lineHeight:'1.1',marginBottom:'16px'},children:[]},{id:uid(),type:'text',tag:'p',content:'Drag-and-drop website builder.',styles:{color:'#6b7280',marginBottom:'24px'},children:[]},{id:uid(),type:'button',tag:'button',content:'Start Building',styles:{background:'#7c3aed',color:'#fff',padding:'14px 28px',borderRadius:'10px',fontWeight:'700',border:'none'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{background:'linear-gradient(135deg,#f0e6ff,#e0d4ff)',borderRadius:'24px',height:'350px'},children:[]}]}]},
    {name:'Hero Dark',nodes:[{id:uid(),type:'section',tag:'section',content:'',name:'Hero Dark',styles:{padding:'100px 32px',textAlign:'center',background:'#0f172a',color:'#fff'},children:[{id:uid(),type:'heading',tag:'h1',content:'The Future is Now',styles:{fontSize:'3.5rem',fontWeight:'800',marginBottom:'16px'},children:[]},{id:uid(),type:'text',tag:'p',content:'Next-gen tools for creators.',styles:{color:'rgba(255,255,255,0.7)',marginBottom:'32px'},children:[]},{id:uid(),type:'button',tag:'button',content:'Join Waitlist',styles:{background:'#7c3aed',color:'#fff',padding:'14px 32px',borderRadius:'10px',fontWeight:'700',border:'none'},children:[]}]}]},
    {name:'Hero Minimal',nodes:[{id:uid(),type:'section',tag:'section',content:'',name:'Hero Minimal',styles:{padding:'120px 32px',textAlign:'center',maxWidth:'800px',margin:'0 auto'},children:[{id:uid(),type:'heading',tag:'h1',content:'Less is More',styles:{fontSize:'4rem',fontWeight:'900',marginBottom:'20px'},children:[]},{id:uid(),type:'text',tag:'p',content:'Clean, minimal design.',styles:{fontSize:'1.25rem',color:'#6b7280',marginBottom:'40px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{display:'flex',gap:'12px',justifyContent:'center'},children:[{id:uid(),type:'button',tag:'button',content:'Get Started',styles:{background:'#111',color:'#fff',padding:'14px 28px',borderRadius:'8px',fontWeight:'600',border:'none'},children:[]},{id:uid(),type:'button',tag:'button',content:'Learn More',styles:{background:'transparent',color:'#111',padding:'14px 28px',borderRadius:'8px',fontWeight:'600',border:'1px solid #e5e7eb'},children:[]}]}]}]},
    {name:'Hero Gradient BG',nodes:[{id:uid(),type:'section',tag:'section',content:'',name:'Hero Gradient',styles:{padding:'100px 32px',textAlign:'center',background:'linear-gradient(180deg,#1e1b4b,#312e81)',color:'#fff'},children:[{id:uid(),type:'text',tag:'span',content:'INTRODUCING',styles:{fontSize:'0.75rem',fontWeight:'700',letterSpacing:'0.1em',color:'#a78bfa',marginBottom:'12px',display:'block'},children:[]},{id:uid(),type:'heading',tag:'h1',content:'Next Generation Platform',styles:{fontSize:'3.5rem',fontWeight:'800',marginBottom:'16px'},children:[]},{id:uid(),type:'text',tag:'p',content:'Everything you need to build modern web applications.',styles:{color:'rgba(255,255,255,0.7)',fontSize:'1.2rem',marginBottom:'32px',maxWidth:'600px',margin:'0 auto 32px'},children:[]},{id:uid(),type:'button',tag:'button',content:'Request Access',styles:{background:'#7c3aed',color:'#fff',padding:'14px 32px',borderRadius:'10px',fontWeight:'700',border:'none'},children:[]}]}]},
  ],
  'Navbar': [
    {name:'Navbar Light',nodes:[{id:uid(),type:'section',tag:'nav',content:'',name:'Navbar',styles:{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'16px 32px',borderBottom:'1px solid #e5e7eb'},children:[{id:uid(),type:'text',tag:'span',content:'Brand',styles:{fontWeight:'800',fontSize:'1.2rem'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{display:'flex',gap:'24px'},children:[{id:uid(),type:'text',tag:'a',content:'Home',styles:{color:'#374151',fontSize:'0.9rem'},children:[]},{id:uid(),type:'text',tag:'a',content:'About',styles:{color:'#374151',fontSize:'0.9rem'},children:[]},{id:uid(),type:'text',tag:'a',content:'Services',styles:{color:'#374151',fontSize:'0.9rem'},children:[]},{id:uid(),type:'text',tag:'a',content:'Contact',styles:{color:'#374151',fontSize:'0.9rem'},children:[]}]},{id:uid(),type:'button',tag:'button',content:'Get Started',styles:{background:'#7c3aed',color:'#fff',padding:'8px 16px',borderRadius:'8px',fontWeight:'600',border:'none',fontSize:'0.85rem'},children:[]}]}]},
    {name:'Navbar Dark',nodes:[{id:uid(),type:'section',tag:'nav',content:'',name:'Navbar Dark',styles:{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'16px 32px',background:'#0f172a'},children:[{id:uid(),type:'text',tag:'span',content:'OmniBuilder',styles:{fontWeight:'800',fontSize:'1.1rem',color:'#fff'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{display:'flex',gap:'24px'},children:[{id:uid(),type:'text',tag:'a',content:'Features',styles:{color:'rgba(255,255,255,0.7)',fontSize:'0.9rem'},children:[]},{id:uid(),type:'text',tag:'a',content:'Pricing',styles:{color:'rgba(255,255,255,0.7)',fontSize:'0.9rem'},children:[]},{id:uid(),type:'text',tag:'a',content:'Docs',styles:{color:'rgba(255,255,255,0.7)',fontSize:'0.9rem'},children:[]}]},{id:uid(),type:'button',tag:'button',content:'Sign Up',styles:{background:'#7c3aed',color:'#fff',padding:'8px 16px',borderRadius:'8px',fontWeight:'600',border:'none'},children:[]}]}]},
    {name:'Navbar Centered',nodes:[{id:uid(),type:'section',tag:'nav',content:'',name:'Navbar Center',styles:{display:'flex',alignItems:'center',justifyContent:'center',gap:'32px',padding:'16px 32px',borderBottom:'1px solid #e5e7eb'},children:[{id:uid(),type:'text',tag:'a',content:'Home',styles:{color:'#374151',fontSize:'0.9rem',fontWeight:'500'},children:[]},{id:uid(),type:'text',tag:'a',content:'About',styles:{color:'#374151',fontSize:'0.9rem',fontWeight:'500'},children:[]},{id:uid(),type:'text',tag:'span',content:'BRAND',styles:{fontWeight:'900',fontSize:'1.3rem',margin:'0 16px'},children:[]},{id:uid(),type:'text',tag:'a',content:'Blog',styles:{color:'#374151',fontSize:'0.9rem',fontWeight:'500'},children:[]},{id:uid(),type:'text',tag:'a',content:'Contact',styles:{color:'#374151',fontSize:'0.9rem',fontWeight:'500'},children:[]}]}]},
  ],
  'Features': [
    {name:'Features 3 Col',nodes:[{id:uid(),type:'section',tag:'section',content:'',name:'Features',styles:{padding:'64px 32px'},children:[{id:uid(),type:'heading',tag:'h2',content:'Why Choose Us',styles:{fontSize:'2rem',fontWeight:'800',textAlign:'center',marginBottom:'40px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'24px',maxWidth:'1000px',margin:'0 auto'},children:[{id:uid(),type:'container',tag:'div',content:'',styles:{padding:'32px',borderRadius:'16px',border:'1px solid #e5e7eb',textAlign:'center'},children:[{id:uid(),type:'heading',tag:'h3',content:'Fast',styles:{fontSize:'1.1rem',fontWeight:'700',marginBottom:'8px'},children:[]},{id:uid(),type:'text',tag:'p',content:'Sub-second load times.',styles:{color:'#6b7280',fontSize:'0.9rem'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{padding:'32px',borderRadius:'16px',border:'1px solid #e5e7eb',textAlign:'center'},children:[{id:uid(),type:'heading',tag:'h3',content:'Responsive',styles:{fontSize:'1.1rem',fontWeight:'700',marginBottom:'8px'},children:[]},{id:uid(),type:'text',tag:'p',content:'Works on all devices.',styles:{color:'#6b7280',fontSize:'0.9rem'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{padding:'32px',borderRadius:'16px',border:'1px solid #e5e7eb',textAlign:'center'},children:[{id:uid(),type:'heading',tag:'h3',content:'SEO Ready',styles:{fontSize:'1.1rem',fontWeight:'700',marginBottom:'8px'},children:[]},{id:uid(),type:'text',tag:'p',content:'Built-in SEO tools.',styles:{color:'#6b7280',fontSize:'0.9rem'},children:[]}]}]}]}]},
    {name:'Features Icon Grid',nodes:[{id:uid(),type:'section',tag:'section',content:'',name:'Icon Features',styles:{padding:'64px 32px',background:'#f9fafb'},children:[{id:uid(),type:'heading',tag:'h2',content:'Everything You Need',styles:{fontSize:'2rem',fontWeight:'800',textAlign:'center',marginBottom:'8px'},children:[]},{id:uid(),type:'text',tag:'p',content:'Powerful features to build anything.',styles:{textAlign:'center',color:'#6b7280',marginBottom:'40px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'32px',maxWidth:'900px',margin:'0 auto'},children:[{id:uid(),type:'container',tag:'div',content:'',styles:{},children:[{id:uid(),type:'container',tag:'div',content:'',styles:{width:'40px',height:'40px',borderRadius:'10px',background:'#ede9fe',marginBottom:'12px'},children:[]},{id:uid(),type:'heading',tag:'h3',content:'Drag & Drop',styles:{fontSize:'1rem',fontWeight:'700',marginBottom:'4px'},children:[]},{id:uid(),type:'text',tag:'p',content:'Visual editing without code.',styles:{color:'#6b7280',fontSize:'0.85rem'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{},children:[{id:uid(),type:'container',tag:'div',content:'',styles:{width:'40px',height:'40px',borderRadius:'10px',background:'#dbeafe',marginBottom:'12px'},children:[]},{id:uid(),type:'heading',tag:'h3',content:'Responsive',styles:{fontSize:'1rem',fontWeight:'700',marginBottom:'4px'},children:[]},{id:uid(),type:'text',tag:'p',content:'Mobile-first design.',styles:{color:'#6b7280',fontSize:'0.85rem'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{},children:[{id:uid(),type:'container',tag:'div',content:'',styles:{width:'40px',height:'40px',borderRadius:'10px',background:'#d1fae5',marginBottom:'12px'},children:[]},{id:uid(),type:'heading',tag:'h3',content:'Fast Deploy',styles:{fontSize:'1rem',fontWeight:'700',marginBottom:'4px'},children:[]},{id:uid(),type:'text',tag:'p',content:'One-click publishing.',styles:{color:'#6b7280',fontSize:'0.85rem'},children:[]}]}]}]}]},
  ],
  'Pricing': [
    {name:'Pricing 3 Tier',nodes:[{id:uid(),type:'section',tag:'section',content:'',name:'Pricing',styles:{padding:'64px 32px',textAlign:'center'},children:[{id:uid(),type:'heading',tag:'h2',content:'Pricing',styles:{fontSize:'2rem',fontWeight:'800',marginBottom:'40px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'24px',maxWidth:'900px',margin:'0 auto'},children:[{id:uid(),type:'container',tag:'div',content:'',styles:{padding:'32px',borderRadius:'16px',border:'1px solid #e5e7eb'},children:[{id:uid(),type:'text',tag:'p',content:'Starter',styles:{fontWeight:'600',marginBottom:'8px'},children:[]},{id:uid(),type:'heading',tag:'h3',content:'$9/mo',styles:{fontSize:'2.5rem',fontWeight:'800',marginBottom:'16px'},children:[]},{id:uid(),type:'button',tag:'button',content:'Choose',styles:{width:'100%',background:'#f3f4f6',color:'#374151',padding:'12px',borderRadius:'8px',fontWeight:'600',border:'none'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{padding:'32px',borderRadius:'16px',border:'2px solid #7c3aed',background:'#faf5ff'},children:[{id:uid(),type:'text',tag:'p',content:'Pro',styles:{fontWeight:'600',color:'#7c3aed',marginBottom:'8px'},children:[]},{id:uid(),type:'heading',tag:'h3',content:'$29/mo',styles:{fontSize:'2.5rem',fontWeight:'800',marginBottom:'16px'},children:[]},{id:uid(),type:'button',tag:'button',content:'Choose',styles:{width:'100%',background:'#7c3aed',color:'#fff',padding:'12px',borderRadius:'8px',fontWeight:'600',border:'none'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{padding:'32px',borderRadius:'16px',border:'1px solid #e5e7eb'},children:[{id:uid(),type:'text',tag:'p',content:'Enterprise',styles:{fontWeight:'600',marginBottom:'8px'},children:[]},{id:uid(),type:'heading',tag:'h3',content:'$99/mo',styles:{fontSize:'2.5rem',fontWeight:'800',marginBottom:'16px'},children:[]},{id:uid(),type:'button',tag:'button',content:'Contact',styles:{width:'100%',background:'#f3f4f6',color:'#374151',padding:'12px',borderRadius:'8px',fontWeight:'600',border:'none'},children:[]}]}]}]}]},
  ],
  'Testimonials': [
    {name:'Testimonial Cards',nodes:[{id:uid(),type:'section',tag:'section',content:'',name:'Testimonials',styles:{padding:'64px 32px',background:'#f9fafb'},children:[{id:uid(),type:'heading',tag:'h2',content:'What Customers Say',styles:{fontSize:'2rem',fontWeight:'800',textAlign:'center',marginBottom:'40px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'24px',maxWidth:'1000px',margin:'0 auto'},children:[{id:uid(),type:'container',tag:'div',content:'',styles:{padding:'24px',borderRadius:'16px',background:'#fff',border:'1px solid #e5e7eb'},children:[{id:uid(),type:'text',tag:'p',content:'Incredible tool. Saved us weeks of work.',styles:{color:'#374151',marginBottom:'16px',fontStyle:'italic'},children:[]},{id:uid(),type:'text',tag:'p',content:'Sarah J. - CEO',styles:{fontWeight:'600',fontSize:'0.85rem'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{padding:'24px',borderRadius:'16px',background:'#fff',border:'1px solid #e5e7eb'},children:[{id:uid(),type:'text',tag:'p',content:'Best builder we have ever used.',styles:{color:'#374151',marginBottom:'16px',fontStyle:'italic'},children:[]},{id:uid(),type:'text',tag:'p',content:'Mike C. - CTO',styles:{fontWeight:'600',fontSize:'0.85rem'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{padding:'24px',borderRadius:'16px',background:'#fff',border:'1px solid #e5e7eb'},children:[{id:uid(),type:'text',tag:'p',content:'Revolutionary product for our team.',styles:{color:'#374151',marginBottom:'16px',fontStyle:'italic'},children:[]},{id:uid(),type:'text',tag:'p',content:'Emma D. - Designer',styles:{fontWeight:'600',fontSize:'0.85rem'},children:[]}]}]}]}]},
  ],
  'CTA': [
    {name:'CTA Banner',nodes:[{id:uid(),type:'section',tag:'section',content:'',name:'CTA',styles:{padding:'64px 32px',background:'linear-gradient(135deg,#7c3aed,#6d28d9)',borderRadius:'24px',margin:'32px',textAlign:'center'},children:[{id:uid(),type:'heading',tag:'h2',content:'Ready to Start?',styles:{fontSize:'2.2rem',fontWeight:'800',color:'#fff',marginBottom:'12px'},children:[]},{id:uid(),type:'text',tag:'p',content:'Join thousands building with us.',styles:{color:'rgba(255,255,255,0.8)',marginBottom:'24px'},children:[]},{id:uid(),type:'button',tag:'button',content:'Start Free',styles:{background:'#fff',color:'#7c3aed',padding:'14px 32px',borderRadius:'10px',fontWeight:'700',border:'none'},children:[]}]}]},
    {name:'CTA Simple',nodes:[{id:uid(),type:'section',tag:'section',content:'',name:'CTA Simple',styles:{padding:'48px 32px',textAlign:'center',background:'#f9fafb',borderRadius:'16px',margin:'24px'},children:[{id:uid(),type:'heading',tag:'h2',content:'Get Started Today',styles:{fontSize:'1.8rem',fontWeight:'800',marginBottom:'12px'},children:[]},{id:uid(),type:'text',tag:'p',content:'No credit card required.',styles:{color:'#6b7280',marginBottom:'20px'},children:[]},{id:uid(),type:'button',tag:'button',content:'Sign Up Free',styles:{background:'#7c3aed',color:'#fff',padding:'12px 28px',borderRadius:'8px',fontWeight:'700',border:'none'},children:[]}]}]},
  ],
  'Footer': [
    {name:'Footer 4 Col',nodes:[{id:uid(),type:'section',tag:'footer',content:'',name:'Footer',styles:{padding:'48px 32px',background:'#0f172a',color:'#fff'},children:[{id:uid(),type:'container',tag:'div',content:'',styles:{display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1fr',gap:'40px',maxWidth:'1000px',margin:'0 auto'},children:[{id:uid(),type:'container',tag:'div',content:'',styles:{},children:[{id:uid(),type:'text',tag:'span',content:'OmniBuilder',styles:{fontWeight:'800',fontSize:'1.2rem'},children:[]},{id:uid(),type:'text',tag:'p',content:'Building the future.',styles:{color:'rgba(255,255,255,0.6)',fontSize:'0.85rem',marginTop:'8px'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{},children:[{id:uid(),type:'text',tag:'p',content:'Product',styles:{fontWeight:'700',fontSize:'0.85rem',marginBottom:'12px'},children:[]},{id:uid(),type:'text',tag:'a',content:'Features',styles:{color:'rgba(255,255,255,0.6)',fontSize:'0.85rem',display:'block',marginBottom:'8px'},children:[]},{id:uid(),type:'text',tag:'a',content:'Pricing',styles:{color:'rgba(255,255,255,0.6)',fontSize:'0.85rem',display:'block'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{},children:[{id:uid(),type:'text',tag:'p',content:'Company',styles:{fontWeight:'700',fontSize:'0.85rem',marginBottom:'12px'},children:[]},{id:uid(),type:'text',tag:'a',content:'About',styles:{color:'rgba(255,255,255,0.6)',fontSize:'0.85rem',display:'block',marginBottom:'8px'},children:[]},{id:uid(),type:'text',tag:'a',content:'Blog',styles:{color:'rgba(255,255,255,0.6)',fontSize:'0.85rem',display:'block'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{},children:[{id:uid(),type:'text',tag:'p',content:'Legal',styles:{fontWeight:'700',fontSize:'0.85rem',marginBottom:'12px'},children:[]},{id:uid(),type:'text',tag:'a',content:'Privacy',styles:{color:'rgba(255,255,255,0.6)',fontSize:'0.85rem',display:'block',marginBottom:'8px'},children:[]},{id:uid(),type:'text',tag:'a',content:'Terms',styles:{color:'rgba(255,255,255,0.6)',fontSize:'0.85rem',display:'block'},children:[]}]}]}]}]},
  ],
  'FAQ': [
    {name:'FAQ Section',nodes:[{id:uid(),type:'section',tag:'section',content:'',name:'FAQ',styles:{padding:'64px 32px',maxWidth:'700px',margin:'0 auto'},children:[{id:uid(),type:'heading',tag:'h2',content:'FAQ',styles:{fontSize:'2rem',fontWeight:'800',textAlign:'center',marginBottom:'40px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{padding:'20px',borderBottom:'1px solid #e5e7eb'},children:[{id:uid(),type:'heading',tag:'h3',content:'How does it work?',styles:{fontSize:'1rem',fontWeight:'700',marginBottom:'8px'},children:[]},{id:uid(),type:'text',tag:'p',content:'Visual drag-and-drop builder.',styles:{color:'#6b7280',fontSize:'0.9rem'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{padding:'20px',borderBottom:'1px solid #e5e7eb'},children:[{id:uid(),type:'heading',tag:'h3',content:'Can I import sites?',styles:{fontSize:'1rem',fontWeight:'700',marginBottom:'8px'},children:[]},{id:uid(),type:'text',tag:'p',content:'Yes. ZIP, Git, or URL.',styles:{color:'#6b7280',fontSize:'0.9rem'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{padding:'20px'},children:[{id:uid(),type:'heading',tag:'h3',content:'Free plan available?',styles:{fontSize:'1rem',fontWeight:'700',marginBottom:'8px'},children:[]},{id:uid(),type:'text',tag:'p',content:'Yes, generous free tier.',styles:{color:'#6b7280',fontSize:'0.9rem'},children:[]}]}]}]},
  ],
  'Contact': [
    {name:'Contact Form',nodes:[{id:uid(),type:'section',tag:'section',content:'',name:'Contact',styles:{padding:'64px 32px',maxWidth:'600px',margin:'0 auto'},children:[{id:uid(),type:'heading',tag:'h2',content:'Get in Touch',styles:{fontSize:'2rem',fontWeight:'800',textAlign:'center',marginBottom:'32px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{display:'grid',gap:'16px'},children:[{id:uid(),type:'container',tag:'div',content:'',styles:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'16px'},children:[{id:uid(),type:'container',tag:'div',content:'',styles:{height:'48px',borderRadius:'10px',border:'1px solid #e5e7eb',background:'#f9fafb'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{height:'48px',borderRadius:'10px',border:'1px solid #e5e7eb',background:'#f9fafb'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{height:'120px',borderRadius:'10px',border:'1px solid #e5e7eb',background:'#f9fafb'},children:[]},{id:uid(),type:'button',tag:'button',content:'Send',styles:{height:'48px',background:'#7c3aed',color:'#fff',borderRadius:'10px',fontWeight:'700',border:'none'},children:[]}]}]}]},
  ],
  'Media': [
    {name:'Image',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'Image',styles:{width:'100%',height:'250px',background:'#f3f4f6',borderRadius:'12px',display:'flex',alignItems:'center',justifyContent:'center'},children:[{id:uid(),type:'text',tag:'span',content:'[Image Placeholder]',styles:{color:'#9ca3af'},children:[]}]}]},
    {name:'Gallery Grid',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'Gallery',styles:{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'8px',padding:'16px'},children:[{id:uid(),type:'container',tag:'div',content:'',styles:{aspectRatio:'1',background:'#f3f4f6',borderRadius:'8px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{aspectRatio:'1',background:'#f3f4f6',borderRadius:'8px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{aspectRatio:'1',background:'#f3f4f6',borderRadius:'8px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{aspectRatio:'1',background:'#f3f4f6',borderRadius:'8px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{aspectRatio:'1',background:'#f3f4f6',borderRadius:'8px'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{aspectRatio:'1',background:'#f3f4f6',borderRadius:'8px'},children:[]}]}]},
    {name:'Video',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'Video',styles:{width:'100%',height:'300px',background:'#1e293b',borderRadius:'12px',display:'flex',alignItems:'center',justifyContent:'center'},children:[{id:uid(),type:'text',tag:'span',content:'[Video Player]',styles:{color:'#94a3b8',fontSize:'1.2rem'},children:[]}]}]},
  ],
  'Utility': [
    {name:'Divider',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'Divider',styles:{borderTop:'1px solid #e5e7eb',margin:'24px 0',height:'1px'},children:[]}]},
    {name:'Spacer SM',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'Spacer',styles:{height:'24px'},children:[]}]},
    {name:'Spacer MD',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'Spacer',styles:{height:'48px'},children:[]}]},
    {name:'Spacer LG',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'Spacer',styles:{height:'96px'},children:[]}]},
    {name:'HTML Embed',nodes:[{id:uid(),type:'text',tag:'div',content:'<!-- Custom HTML -->',name:'HTML',styles:{padding:'16px',background:'#f9fafb',border:'1px dashed #d1d5db',borderRadius:'8px',fontFamily:'monospace',fontSize:'0.8rem'},children:[]}]},
  ],
  'Data': [
    {name:'Stats Row',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'Stats',styles:{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'24px',padding:'48px 32px',textAlign:'center'},children:[{id:uid(),type:'container',tag:'div',content:'',styles:{},children:[{id:uid(),type:'heading',tag:'h3',content:'10K+',styles:{fontSize:'2rem',fontWeight:'800',color:'#7c3aed'},children:[]},{id:uid(),type:'text',tag:'p',content:'Users',styles:{color:'#6b7280',fontSize:'0.85rem'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{},children:[{id:uid(),type:'heading',tag:'h3',content:'50M+',styles:{fontSize:'2rem',fontWeight:'800',color:'#7c3aed'},children:[]},{id:uid(),type:'text',tag:'p',content:'Pages Built',styles:{color:'#6b7280',fontSize:'0.85rem'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{},children:[{id:uid(),type:'heading',tag:'h3',content:'99.9%',styles:{fontSize:'2rem',fontWeight:'800',color:'#7c3aed'},children:[]},{id:uid(),type:'text',tag:'p',content:'Uptime',styles:{color:'#6b7280',fontSize:'0.85rem'},children:[]}]},{id:uid(),type:'container',tag:'div',content:'',styles:{},children:[{id:uid(),type:'heading',tag:'h3',content:'24/7',styles:{fontSize:'2rem',fontWeight:'800',color:'#7c3aed'},children:[]},{id:uid(),type:'text',tag:'p',content:'Support',styles:{color:'#6b7280',fontSize:'0.85rem'},children:[]}]}]}]},
    {name:'Progress Bar',nodes:[{id:uid(),type:'container',tag:'div',content:'',name:'Progress',styles:{padding:'8px 0'},children:[{id:uid(),type:'text',tag:'span',content:'Progress 65%',styles:{fontSize:'0.8rem',fontWeight:'600',marginBottom:'4px',display:'block'},children:[]},{id:uid(),type:'container',tag:'div',content:'',styles:{height:'8px',background:'#e5e7eb',borderRadius:'4px',overflow:'hidden'},children:[{id:uid(),type:'container',tag:'div',content:'',styles:{height:'100%',width:'65%',background:'#7c3aed',borderRadius:'4px'},children:[]}]}]}]},
  ],
};

export const TEMPLATES: Record<string, string[]> = {
  'SaaS Landing': ['Navbar Light','Hero Centered','Features 3 Col','Pricing 3 Tier','Testimonial Cards','CTA Banner','Footer 4 Col'],
  'Agency': ['Navbar Light','Hero Split','Features Icon Grid','Testimonial Cards','Contact Form','Footer 4 Col'],
  'Portfolio': ['Navbar Dark','Hero Minimal','Features 3 Col','CTA Simple','Footer 4 Col'],
  'Business': ['Navbar Light','Hero Centered','Features 3 Col','Pricing 3 Tier','FAQ Section','Footer 4 Col'],
  'Startup': ['Navbar Dark','Hero Dark','Features Icon Grid','Pricing 3 Tier','CTA Banner','Footer 4 Col'],
  'Minimal': ['Navbar Centered','Hero Minimal','Features 3 Col','CTA Simple','Footer 4 Col'],
};
