// OmniBuilder Component Registry
export interface BNode {
  id: string; type: string; tag: string; content: string;
  styles: Record<string,string>; children: BNode[];
  locked?: boolean; hidden?: boolean; name?: string;
}
let _c = 0;
export function uid(): string { return 'n' + (++_c) + Date.now().toString(36) + Math.random().toString(36).slice(2,5); }
export function cloneNode(n: BNode): BNode { return {...n, id: uid(), children: n.children.map(cloneNode)}; }

export interface CompDef { name: string; nodes: BNode[]; }

// Helper
function s(id:string,type:string,tag:string,content:string,styles:Record<string,string>,children:BNode[]=[],name?:string): BNode {
  return {id,type,tag,content,styles,children,name};
}

export const CATEGORIES: Record<string, CompDef[]> = {
'Layout':[
{name:'Section',nodes:[s(uid(),'section','section','',{padding:'48px 32px'},[],'Section')]},
{name:'Container',nodes:[s(uid(),'container','div','',{padding:'24px',maxWidth:'1200px',margin:'0 auto'},[],'Container')]},
{name:'2 Columns',nodes:[s(uid(),'container','div','',{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'24px',padding:'24px'},[s(uid(),'container','div','',{padding:'16px',background:'#f9fafb',borderRadius:'8px',minHeight:'120px'},[]),s(uid(),'container','div','',{padding:'16px',background:'#f9fafb',borderRadius:'8px',minHeight:'120px'},[])],'2 Columns')]},
{name:'3 Columns',nodes:[s(uid(),'container','div','',{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'24px',padding:'24px'},[s(uid(),'container','div','',{padding:'16px',background:'#f9fafb',borderRadius:'8px',minHeight:'120px'},[]),s(uid(),'container','div','',{padding:'16px',background:'#f9fafb',borderRadius:'8px',minHeight:'120px'},[]),s(uid(),'container','div','',{padding:'16px',background:'#f9fafb',borderRadius:'8px',minHeight:'120px'},[])],'3 Columns')]},
{name:'4 Columns',nodes:[s(uid(),'container','div','',{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'16px',padding:'24px'},[s(uid(),'container','div','',{padding:'12px',background:'#f9fafb',borderRadius:'8px',minHeight:'100px'},[]),s(uid(),'container','div','',{padding:'12px',background:'#f9fafb',borderRadius:'8px',minHeight:'100px'},[]),s(uid(),'container','div','',{padding:'12px',background:'#f9fafb',borderRadius:'8px',minHeight:'100px'},[]),s(uid(),'container','div','',{padding:'12px',background:'#f9fafb',borderRadius:'8px',minHeight:'100px'},[])],'4 Columns')]},
{name:'Sidebar Left',nodes:[s(uid(),'container','div','',{display:'grid',gridTemplateColumns:'240px 1fr',gap:'24px',padding:'24px'},[s(uid(),'container','aside','',{padding:'20px',background:'#f9fafb',borderRadius:'12px'},[],'Sidebar'),s(uid(),'container','main','',{padding:'20px',border:'1px solid #e5e7eb',borderRadius:'12px',minHeight:'300px'},[],'Main')],'Sidebar Left')]},
{name:'Flex Row',nodes:[s(uid(),'container','div','',{display:'flex',gap:'16px',alignItems:'center',padding:'16px'},[],'Flex Row')]},
{name:'Flex Column',nodes:[s(uid(),'container','div','',{display:'flex',flexDirection:'column',gap:'16px',padding:'16px'},[],'Flex Column')]},
{name:'Card',nodes:[s(uid(),'container','div','',{padding:'24px',borderRadius:'16px',border:'1px solid #e5e7eb',background:'#fff',boxShadow:'0 1px 3px rgba(0,0,0,0.08)'},[s(uid(),'heading','h3','Card Title',{fontSize:'1.1rem',fontWeight:'700',marginBottom:'8px'},[]),s(uid(),'text','p','Card description.',{color:'#6b7280',fontSize:'0.9rem'},[])],'Card')]},
{name:'Panel',nodes:[s(uid(),'container','div','',{padding:'24px',borderRadius:'12px',background:'#f8fafc',border:'1px solid #e2e8f0'},[],'Panel')]},
{name:'Stack',nodes:[s(uid(),'container','div','',{display:'flex',flexDirection:'column',gap:'8px'},[],'Stack')]},
],
'Typography':[
{name:'H1',nodes:[s(uid(),'heading','h1','Heading 1',{fontSize:'3rem',fontWeight:'800',letterSpacing:'-0.02em'},[])]},
{name:'H2',nodes:[s(uid(),'heading','h2','Heading 2',{fontSize:'2rem',fontWeight:'700'},[])]},
{name:'H3',nodes:[s(uid(),'heading','h3','Heading 3',{fontSize:'1.5rem',fontWeight:'700'},[])]},
{name:'H4',nodes:[s(uid(),'heading','h4','Heading 4',{fontSize:'1.25rem',fontWeight:'600'},[])]},
{name:'Paragraph',nodes:[s(uid(),'text','p','Your paragraph text here. Click to edit.',{color:'#374151',lineHeight:'1.7'},[])]},
{name:'Lead',nodes:[s(uid(),'text','p','Lead paragraph with larger text.',{fontSize:'1.25rem',color:'#4b5563',lineHeight:'1.6'},[])]},
{name:'Small',nodes:[s(uid(),'text','p','Small supporting text.',{color:'#6b7280',fontSize:'0.875rem'},[])]},
{name:'Blockquote',nodes:[s(uid(),'text','blockquote','An important quote.',{borderLeft:'4px solid #7c3aed',paddingLeft:'16px',fontStyle:'italic',color:'#4b5563'},[])]},
{name:'List',nodes:[s(uid(),'container','ul','',{paddingLeft:'20px',lineHeight:'2'},[s(uid(),'text','li','First item',{},[]),s(uid(),'text','li','Second item',{},[]),s(uid(),'text','li','Third item',{},[])],'List')]},
{name:'Badge',nodes:[s(uid(),'text','span','NEW',{background:'#7c3aed',color:'#fff',padding:'4px 12px',borderRadius:'20px',fontSize:'0.75rem',fontWeight:'700'},[])]},
{name:'Code',nodes:[s(uid(),'text','pre','const x = 42;',{background:'#1e293b',color:'#a5f3fc',padding:'16px',borderRadius:'8px',fontSize:'0.85rem',fontFamily:'monospace'},[])]},
{name:'Link',nodes:[s(uid(),'text','a','Click here',{color:'#7c3aed',fontWeight:'500',textDecoration:'underline'},[])]},
],
'Buttons':[
{name:'Primary',nodes:[s(uid(),'button','button','Get Started',{background:'#7c3aed',color:'#fff',padding:'12px 24px',borderRadius:'8px',fontWeight:'600',border:'none'},[])]},
{name:'Secondary',nodes:[s(uid(),'button','button','Learn More',{background:'transparent',color:'#7c3aed',padding:'12px 24px',borderRadius:'8px',fontWeight:'600',border:'2px solid #7c3aed'},[])]},
{name:'Dark',nodes:[s(uid(),'button','button','Continue',{background:'#111827',color:'#fff',padding:'12px 24px',borderRadius:'8px',fontWeight:'600',border:'none'},[])]},
{name:'Ghost',nodes:[s(uid(),'button','button','Cancel',{background:'transparent',color:'#6b7280',padding:'12px 24px',borderRadius:'8px',fontWeight:'500',border:'1px solid #e5e7eb'},[])]},
{name:'Pill',nodes:[s(uid(),'button','button','Subscribe',{background:'#7c3aed',color:'#fff',padding:'10px 28px',borderRadius:'999px',fontWeight:'600',border:'none'},[])]},
{name:'Large CTA',nodes:[s(uid(),'button','button','Start Free Trial',{background:'linear-gradient(135deg,#7c3aed,#6d28d9)',color:'#fff',padding:'16px 40px',borderRadius:'12px',fontWeight:'700',border:'none',fontSize:'1.1rem',boxShadow:'0 4px 14px rgba(124,58,237,0.3)'},[])]},
{name:'Icon Button',nodes:[s(uid(),'button','button','-> Download',{background:'#f3f4f6',color:'#374151',padding:'10px 20px',borderRadius:'8px',fontWeight:'600',border:'1px solid #e5e7eb'},[])]},
],
'Hero':[
{name:'Hero Centered',nodes:[s(uid(),'section','section','',{padding:'80px 32px',textAlign:'center',background:'linear-gradient(135deg,#667eea,#764ba2)'},[s(uid(),'heading','h1','Build Something Amazing',{fontSize:'3.5rem',fontWeight:'800',color:'#fff',marginBottom:'16px'},[]),s(uid(),'text','p','The all-in-one platform for modern teams.',{fontSize:'1.2rem',color:'rgba(255,255,255,0.85)',marginBottom:'32px'},[]),s(uid(),'button','button','Get Started',{background:'#fff',color:'#764ba2',padding:'14px 32px',borderRadius:'8px',fontWeight:'700',border:'none'},[])],'Hero Centered')]},
{name:'Hero Split',nodes:[s(uid(),'section','section','',{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'40px',padding:'80px 48px',alignItems:'center'},[s(uid(),'container','div','',{},[s(uid(),'heading','h1','Design Without Limits',{fontSize:'3rem',fontWeight:'800',lineHeight:'1.1',marginBottom:'16px'},[]),s(uid(),'text','p','Create stunning websites visually.',{color:'#6b7280',marginBottom:'24px'},[]),s(uid(),'button','button','Start Building',{background:'#7c3aed',color:'#fff',padding:'14px 28px',borderRadius:'10px',fontWeight:'700',border:'none'},[])]),s(uid(),'container','div','',{background:'linear-gradient(135deg,#f0e6ff,#e0d4ff)',borderRadius:'24px',height:'350px'},[])],'Hero Split')]},
{name:'Hero Dark',nodes:[s(uid(),'section','section','',{padding:'100px 32px',textAlign:'center',background:'#0f172a',color:'#fff'},[s(uid(),'heading','h1','The Future is Now',{fontSize:'3.5rem',fontWeight:'800',marginBottom:'16px'},[]),s(uid(),'text','p','Next-gen tools for creators.',{color:'rgba(255,255,255,0.7)',marginBottom:'32px'},[]),s(uid(),'button','button','Join Waitlist',{background:'#7c3aed',color:'#fff',padding:'14px 32px',borderRadius:'10px',fontWeight:'700',border:'none'},[])],'Hero Dark')]},
{name:'Hero Minimal',nodes:[s(uid(),'section','section','',{padding:'120px 32px',textAlign:'center',maxWidth:'800px',margin:'0 auto'},[s(uid(),'heading','h1','Less is More',{fontSize:'4rem',fontWeight:'900',marginBottom:'20px'},[]),s(uid(),'text','p','Clean design that speaks volumes.',{fontSize:'1.25rem',color:'#6b7280',marginBottom:'40px'},[]),s(uid(),'container','div','',{display:'flex',gap:'12px',justifyContent:'center'},[s(uid(),'button','button','Get Started',{background:'#111',color:'#fff',padding:'14px 28px',borderRadius:'8px',fontWeight:'600',border:'none'},[]),s(uid(),'button','button','Learn More',{background:'transparent',color:'#111',padding:'14px 28px',borderRadius:'8px',fontWeight:'600',border:'1px solid #e5e7eb'},[])])],'Hero Minimal')]},
{name:'Hero Gradient',nodes:[s(uid(),'section','section','',{padding:'100px 32px',textAlign:'center',background:'linear-gradient(180deg,#1e1b4b,#312e81)',color:'#fff'},[s(uid(),'text','span','INTRODUCING',{fontSize:'0.75rem',fontWeight:'700',letterSpacing:'0.1em',color:'#a78bfa',display:'block',marginBottom:'12px'},[]),s(uid(),'heading','h1','Next Generation Platform',{fontSize:'3.5rem',fontWeight:'800',marginBottom:'16px'},[]),s(uid(),'text','p','Everything you need.',{color:'rgba(255,255,255,0.7)',fontSize:'1.2rem',marginBottom:'32px'},[]),s(uid(),'button','button','Request Access',{background:'#7c3aed',color:'#fff',padding:'14px 32px',borderRadius:'10px',fontWeight:'700',border:'none'},[])],'Hero Gradient')]},
],
'Navbar':[
{name:'Navbar Light',nodes:[s(uid(),'section','nav','',{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'16px 32px',borderBottom:'1px solid #e5e7eb'},[s(uid(),'text','span','Brand',{fontWeight:'800',fontSize:'1.2rem'},[]),s(uid(),'container','div','',{display:'flex',gap:'24px'},[s(uid(),'text','a','Home',{color:'#374151',fontSize:'0.9rem'},[]),s(uid(),'text','a','About',{color:'#374151',fontSize:'0.9rem'},[]),s(uid(),'text','a','Services',{color:'#374151',fontSize:'0.9rem'},[]),s(uid(),'text','a','Contact',{color:'#374151',fontSize:'0.9rem'},[])]),s(uid(),'button','button','Get Started',{background:'#7c3aed',color:'#fff',padding:'8px 16px',borderRadius:'8px',fontWeight:'600',border:'none',fontSize:'0.85rem'},[])],'Navbar')]},
{name:'Navbar Dark',nodes:[s(uid(),'section','nav','',{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'16px 32px',background:'#0f172a'},[s(uid(),'text','span','OmniBuilder',{fontWeight:'800',fontSize:'1.1rem',color:'#fff'},[]),s(uid(),'container','div','',{display:'flex',gap:'24px'},[s(uid(),'text','a','Features',{color:'rgba(255,255,255,0.7)',fontSize:'0.9rem'},[]),s(uid(),'text','a','Pricing',{color:'rgba(255,255,255,0.7)',fontSize:'0.9rem'},[]),s(uid(),'text','a','Docs',{color:'rgba(255,255,255,0.7)',fontSize:'0.9rem'},[])]),s(uid(),'button','button','Sign Up',{background:'#7c3aed',color:'#fff',padding:'8px 16px',borderRadius:'8px',fontWeight:'600',border:'none'},[])],'Navbar Dark')]},
],
'Features':[
{name:'Features 3 Col',nodes:[s(uid(),'section','section','',{padding:'64px 32px'},[s(uid(),'heading','h2','Why Choose Us',{fontSize:'2rem',fontWeight:'800',textAlign:'center',marginBottom:'40px'},[]),s(uid(),'container','div','',{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'24px',maxWidth:'1000px',margin:'0 auto'},[s(uid(),'container','div','',{padding:'32px',borderRadius:'16px',border:'1px solid #e5e7eb',textAlign:'center'},[s(uid(),'heading','h3','Fast',{fontSize:'1.1rem',fontWeight:'700',marginBottom:'8px'},[]),s(uid(),'text','p','Sub-second loads.',{color:'#6b7280',fontSize:'0.9rem'},[])]),s(uid(),'container','div','',{padding:'32px',borderRadius:'16px',border:'1px solid #e5e7eb',textAlign:'center'},[s(uid(),'heading','h3','Responsive',{fontSize:'1.1rem',fontWeight:'700',marginBottom:'8px'},[]),s(uid(),'text','p','All devices.',{color:'#6b7280',fontSize:'0.9rem'},[])]),s(uid(),'container','div','',{padding:'32px',borderRadius:'16px',border:'1px solid #e5e7eb',textAlign:'center'},[s(uid(),'heading','h3','SEO',{fontSize:'1.1rem',fontWeight:'700',marginBottom:'8px'},[]),s(uid(),'text','p','Optimized.',{color:'#6b7280',fontSize:'0.9rem'},[])])])],'Features')]},
],
'Pricing':[
{name:'Pricing 3 Tier',nodes:[s(uid(),'section','section','',{padding:'64px 32px',textAlign:'center'},[s(uid(),'heading','h2','Pricing',{fontSize:'2rem',fontWeight:'800',marginBottom:'40px'},[]),s(uid(),'container','div','',{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'24px',maxWidth:'900px',margin:'0 auto'},[s(uid(),'container','div','',{padding:'32px',borderRadius:'16px',border:'1px solid #e5e7eb'},[s(uid(),'text','p','Starter',{fontWeight:'600',marginBottom:'8px'},[]),s(uid(),'heading','h3','$9/mo',{fontSize:'2.5rem',fontWeight:'800',marginBottom:'16px'},[]),s(uid(),'button','button','Choose',{width:'100%',background:'#f3f4f6',color:'#374151',padding:'12px',borderRadius:'8px',fontWeight:'600',border:'none'},[])]),s(uid(),'container','div','',{padding:'32px',borderRadius:'16px',border:'2px solid #7c3aed',background:'#faf5ff'},[s(uid(),'text','p','Pro',{fontWeight:'600',color:'#7c3aed',marginBottom:'8px'},[]),s(uid(),'heading','h3','$29/mo',{fontSize:'2.5rem',fontWeight:'800',marginBottom:'16px'},[]),s(uid(),'button','button','Choose',{width:'100%',background:'#7c3aed',color:'#fff',padding:'12px',borderRadius:'8px',fontWeight:'600',border:'none'},[])]),s(uid(),'container','div','',{padding:'32px',borderRadius:'16px',border:'1px solid #e5e7eb'},[s(uid(),'text','p','Enterprise',{fontWeight:'600',marginBottom:'8px'},[]),s(uid(),'heading','h3','$99/mo',{fontSize:'2.5rem',fontWeight:'800',marginBottom:'16px'},[]),s(uid(),'button','button','Contact',{width:'100%',background:'#f3f4f6',color:'#374151',padding:'12px',borderRadius:'8px',fontWeight:'600',border:'none'},[])])])],'Pricing')]},
],
'Testimonials':[
{name:'Testimonials',nodes:[s(uid(),'section','section','',{padding:'64px 32px',background:'#f9fafb'},[s(uid(),'heading','h2','Customer Reviews',{fontSize:'2rem',fontWeight:'800',textAlign:'center',marginBottom:'40px'},[]),s(uid(),'container','div','',{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'24px',maxWidth:'1000px',margin:'0 auto'},[s(uid(),'container','div','',{padding:'24px',borderRadius:'16px',background:'#fff',border:'1px solid #e5e7eb'},[s(uid(),'text','p','Amazing tool.',{color:'#374151',marginBottom:'12px',fontStyle:'italic'},[]),s(uid(),'text','p','Sarah - CEO',{fontWeight:'600',fontSize:'0.85rem'},[])]),s(uid(),'container','div','',{padding:'24px',borderRadius:'16px',background:'#fff',border:'1px solid #e5e7eb'},[s(uid(),'text','p','Saved us weeks.',{color:'#374151',marginBottom:'12px',fontStyle:'italic'},[]),s(uid(),'text','p','Mike - CTO',{fontWeight:'600',fontSize:'0.85rem'},[])]),s(uid(),'container','div','',{padding:'24px',borderRadius:'16px',background:'#fff',border:'1px solid #e5e7eb'},[s(uid(),'text','p','Best builder ever.',{color:'#374151',marginBottom:'12px',fontStyle:'italic'},[]),s(uid(),'text','p','Emma - Designer',{fontWeight:'600',fontSize:'0.85rem'},[])])])],'Testimonials')]},
],
'CTA':[
{name:'CTA Banner',nodes:[s(uid(),'section','section','',{padding:'64px 32px',background:'linear-gradient(135deg,#7c3aed,#6d28d9)',borderRadius:'24px',margin:'32px',textAlign:'center'},[s(uid(),'heading','h2','Ready to Start?',{fontSize:'2.2rem',fontWeight:'800',color:'#fff',marginBottom:'12px'},[]),s(uid(),'text','p','Join thousands of creators.',{color:'rgba(255,255,255,0.8)',marginBottom:'24px'},[]),s(uid(),'button','button','Start Free',{background:'#fff',color:'#7c3aed',padding:'14px 32px',borderRadius:'10px',fontWeight:'700',border:'none'},[])],'CTA')]},
{name:'CTA Simple',nodes:[s(uid(),'section','section','',{padding:'48px 32px',textAlign:'center',background:'#f9fafb',borderRadius:'16px',margin:'24px'},[s(uid(),'heading','h2','Get Started Today',{fontSize:'1.8rem',fontWeight:'800',marginBottom:'12px'},[]),s(uid(),'text','p','No credit card required.',{color:'#6b7280',marginBottom:'20px'},[]),s(uid(),'button','button','Sign Up',{background:'#7c3aed',color:'#fff',padding:'12px 28px',borderRadius:'8px',fontWeight:'700',border:'none'},[])],'CTA Simple')]},
],
'Footer':[
{name:'Footer',nodes:[s(uid(),'section','footer','',{padding:'48px 32px',background:'#0f172a',color:'#fff'},[s(uid(),'container','div','',{display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1fr',gap:'40px',maxWidth:'1000px',margin:'0 auto'},[s(uid(),'container','div','',{},[s(uid(),'text','span','OmniBuilder',{fontWeight:'800',fontSize:'1.2rem'},[]),s(uid(),'text','p','Building the future.',{color:'rgba(255,255,255,0.6)',fontSize:'0.85rem',marginTop:'8px'},[])]),s(uid(),'container','div','',{},[s(uid(),'text','p','Product',{fontWeight:'700',fontSize:'0.85rem',marginBottom:'12px'},[]),s(uid(),'text','a','Features',{color:'rgba(255,255,255,0.6)',fontSize:'0.85rem',display:'block',marginBottom:'8px'},[]),s(uid(),'text','a','Pricing',{color:'rgba(255,255,255,0.6)',fontSize:'0.85rem',display:'block'},[])]),s(uid(),'container','div','',{},[s(uid(),'text','p','Company',{fontWeight:'700',fontSize:'0.85rem',marginBottom:'12px'},[]),s(uid(),'text','a','About',{color:'rgba(255,255,255,0.6)',fontSize:'0.85rem',display:'block',marginBottom:'8px'},[]),s(uid(),'text','a','Blog',{color:'rgba(255,255,255,0.6)',fontSize:'0.85rem',display:'block'},[])]),s(uid(),'container','div','',{},[s(uid(),'text','p','Legal',{fontWeight:'700',fontSize:'0.85rem',marginBottom:'12px'},[]),s(uid(),'text','a','Privacy',{color:'rgba(255,255,255,0.6)',fontSize:'0.85rem',display:'block',marginBottom:'8px'},[]),s(uid(),'text','a','Terms',{color:'rgba(255,255,255,0.6)',fontSize:'0.85rem',display:'block'},[])])])],'Footer')]},
],
'FAQ':[
{name:'FAQ',nodes:[s(uid(),'section','section','',{padding:'64px 32px',maxWidth:'700px',margin:'0 auto'},[s(uid(),'heading','h2','FAQ',{fontSize:'2rem',fontWeight:'800',textAlign:'center',marginBottom:'40px'},[]),s(uid(),'container','div','',{padding:'20px',borderBottom:'1px solid #e5e7eb'},[s(uid(),'heading','h3','How does it work?',{fontSize:'1rem',fontWeight:'700',marginBottom:'8px'},[]),s(uid(),'text','p','Drag and drop builder.',{color:'#6b7280',fontSize:'0.9rem'},[])]),s(uid(),'container','div','',{padding:'20px',borderBottom:'1px solid #e5e7eb'},[s(uid(),'heading','h3','Can I import sites?',{fontSize:'1rem',fontWeight:'700',marginBottom:'8px'},[]),s(uid(),'text','p','Yes, from ZIP/Git/URL.',{color:'#6b7280',fontSize:'0.9rem'},[])]),s(uid(),'container','div','',{padding:'20px'},[s(uid(),'heading','h3','Free plan?',{fontSize:'1rem',fontWeight:'700',marginBottom:'8px'},[]),s(uid(),'text','p','Yes, generous free tier.',{color:'#6b7280',fontSize:'0.9rem'},[])])],'FAQ')]},
],
'Contact':[
{name:'Contact Form',nodes:[s(uid(),'section','section','',{padding:'64px 32px',maxWidth:'600px',margin:'0 auto'},[s(uid(),'heading','h2','Contact Us',{fontSize:'2rem',fontWeight:'800',textAlign:'center',marginBottom:'32px'},[]),s(uid(),'container','div','',{display:'grid',gap:'16px'},[s(uid(),'container','div','',{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'16px'},[s(uid(),'container','div','',{height:'48px',borderRadius:'10px',border:'1px solid #e5e7eb',background:'#f9fafb'},[]),s(uid(),'container','div','',{height:'48px',borderRadius:'10px',border:'1px solid #e5e7eb',background:'#f9fafb'},[])]),s(uid(),'container','div','',{height:'120px',borderRadius:'10px',border:'1px solid #e5e7eb',background:'#f9fafb'},[]),s(uid(),'button','button','Send Message',{height:'48px',background:'#7c3aed',color:'#fff',borderRadius:'10px',fontWeight:'700',border:'none'},[])])],'Contact')]},
],
'Media':[
{name:'Image',nodes:[s(uid(),'container','div','',{width:'100%',height:'250px',background:'#f3f4f6',borderRadius:'12px',display:'flex',alignItems:'center',justifyContent:'center'},[s(uid(),'text','span','[Image]',{color:'#9ca3af'},'')],'Image')]},
{name:'Gallery',nodes:[s(uid(),'container','div','',{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'8px',padding:'16px'},[s(uid(),'container','div','',{aspectRatio:'1',background:'#f3f4f6',borderRadius:'8px'},[]),s(uid(),'container','div','',{aspectRatio:'1',background:'#f3f4f6',borderRadius:'8px'},[]),s(uid(),'container','div','',{aspectRatio:'1',background:'#f3f4f6',borderRadius:'8px'},[]),s(uid(),'container','div','',{aspectRatio:'1',background:'#f3f4f6',borderRadius:'8px'},[]),s(uid(),'container','div','',{aspectRatio:'1',background:'#f3f4f6',borderRadius:'8px'},[]),s(uid(),'container','div','',{aspectRatio:'1',background:'#f3f4f6',borderRadius:'8px'},[])],'Gallery')]},
{name:'Video',nodes:[s(uid(),'container','div','',{width:'100%',height:'300px',background:'#1e293b',borderRadius:'12px',display:'flex',alignItems:'center',justifyContent:'center'},[s(uid(),'text','span','[Video]',{color:'#94a3b8',fontSize:'1.2rem'},'')],'Video')]},
],
'Utility':[
{name:'Divider',nodes:[s(uid(),'container','div','',{borderTop:'1px solid #e5e7eb',margin:'24px 0',height:'1px'},[],'Divider')]},
{name:'Spacer SM',nodes:[s(uid(),'container','div','',{height:'24px'},[],'Spacer')]},
{name:'Spacer MD',nodes:[s(uid(),'container','div','',{height:'48px'},[],'Spacer')]},
{name:'Spacer LG',nodes:[s(uid(),'container','div','',{height:'96px'},[],'Spacer')]},
{name:'HTML',nodes:[s(uid(),'text','div','<!-- Custom HTML -->',{padding:'16px',background:'#f9fafb',border:'1px dashed #d1d5db',borderRadius:'8px',fontFamily:'monospace',fontSize:'0.8rem'},[],'HTML')]},
],
'Data':[
{name:'Stats',nodes:[s(uid(),'container','div','',{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'24px',padding:'48px 32px',textAlign:'center'},[s(uid(),'container','div','',{},[s(uid(),'heading','h3','10K+',{fontSize:'2rem',fontWeight:'800',color:'#7c3aed'},[]),s(uid(),'text','p','Users',{color:'#6b7280',fontSize:'0.85rem'},[])]),s(uid(),'container','div','',{},[s(uid(),'heading','h3','50M+',{fontSize:'2rem',fontWeight:'800',color:'#7c3aed'},[]),s(uid(),'text','p','Pages',{color:'#6b7280',fontSize:'0.85rem'},[])]),s(uid(),'container','div','',{},[s(uid(),'heading','h3','99.9%',{fontSize:'2rem',fontWeight:'800',color:'#7c3aed'},[]),s(uid(),'text','p','Uptime',{color:'#6b7280',fontSize:'0.85rem'},[])]),s(uid(),'container','div','',{},[s(uid(),'heading','h3','24/7',{fontSize:'2rem',fontWeight:'800',color:'#7c3aed'},[]),s(uid(),'text','p','Support',{color:'#6b7280',fontSize:'0.85rem'},[])])],'Stats')]},
{name:'Progress',nodes:[s(uid(),'container','div','',{padding:'8px 0'},[s(uid(),'text','span','65%',{fontSize:'0.8rem',fontWeight:'600',display:'block',marginBottom:'4px'},[]),s(uid(),'container','div','',{height:'8px',background:'#e5e7eb',borderRadius:'4px',overflow:'hidden'},[s(uid(),'container','div','',{height:'100%',width:'65%',background:'#7c3aed',borderRadius:'4px'},[])])],'Progress')]},
],
};

export const TEMPLATES: Record<string,string[]> = {
'SaaS Landing':['Navbar Light','Hero Centered','Features 3 Col','Pricing 3 Tier','Testimonials','CTA Banner','Footer'],
'Agency':['Navbar Light','Hero Split','Features 3 Col','Testimonials','Contact Form','Footer'],
'Portfolio':['Navbar Dark','Hero Minimal','Features 3 Col','CTA Simple','Footer'],
'Business':['Navbar Light','Hero Centered','Features 3 Col','Pricing 3 Tier','FAQ','Footer'],
'Startup':['Navbar Dark','Hero Dark','Features 3 Col','Pricing 3 Tier','CTA Banner','Footer'],
'Minimal':['Navbar Light','Hero Minimal','CTA Simple','Footer'],
'Restaurant':['Navbar Light','Hero Centered','Features 3 Col','Testimonials','Contact Form','Footer'],
'Hotel':['Navbar Dark','Hero Gradient','Features 3 Col','Testimonials','CTA Banner','Footer'],
'Medical':['Navbar Light','Hero Split','Features 3 Col','FAQ','Contact Form','Footer'],
'Gym':['Navbar Dark','Hero Dark','Features 3 Col','Pricing 3 Tier','Testimonials','CTA Banner','Footer'],
'Real Estate':['Navbar Light','Hero Split','Features 3 Col','Testimonials','Contact Form','Footer'],
'Ecommerce':['Navbar Light','Hero Centered','Features 3 Col','Pricing 3 Tier','Testimonials','FAQ','Footer'],
'Blog':['Navbar Light','Hero Minimal','Features 3 Col','CTA Simple','Footer'],
'Dashboard':['Navbar Dark','Hero Dark','Features 3 Col','Footer'],
'Coming Soon':['Hero Gradient','CTA Banner'],
'404 Page':['Hero Minimal'],
};
