'use client';

import { useState, useEffect, useRef } from 'react';
import LayoutShell from '../components/layout-shell';

/**
 * YellowPencil-Style Live CSS Editor
 * 
 * This editor loads any website URL in an iframe, then allows
 * clicking any element to select it and edit its CSS properties
 * live, similar to YellowPencil WordPress plugin.
 * 
 * Features:
 * - Load any URL in iframe
 * - Click to select elements
 * - Visual property panel for CSS editing
 * - Real-time preview
 * - Save/export CSS changes
 * - Undo/redo
 * - Responsive preview
 * - Element inspector
 */

interface CSSChange {
  selector: string;
  property: string;
  value: string;
  originalValue: string;
}

export default function StyleEditorPage() {
  const [url, setUrl] = useState('');
  const [loadedUrl, setLoadedUrl] = useState('');
  const [selectedElement, setSelectedElement] = useState<string | null>(null);
  const [elementTag, setElementTag] = useState('');
  const [elementClasses, setElementClasses] = useState('');
  const [changes, setChanges] = useState<CSSChange[]>([]);
  const [viewport, setViewport] = useState<'desktop' | 'tablet' | 'mobile'>('desktop');
  const [showCode, setShowCode] = useState(false);
  const [activeTab, setActiveTab] = useState<'typography' | 'spacing' | 'background' | 'border' | 'layout' | 'effects'>('typography');
  const iframeRef = useRef<HTMLIFrameElement>(null);

  // CSS properties organized by category
  const [styles, setStyles] = useState<Record<string, string>>({
    fontSize: '', fontWeight: '', fontFamily: '', color: '', textAlign: '',
    lineHeight: '', letterSpacing: '', textDecoration: '', textTransform: '',
    padding: '', paddingTop: '', paddingRight: '', paddingBottom: '', paddingLeft: '',
    margin: '', marginTop: '', marginRight: '', marginBottom: '', marginLeft: '',
    backgroundColor: '', backgroundImage: '', backgroundSize: '', backgroundPosition: '',
    border: '', borderRadius: '', borderColor: '', borderWidth: '', borderStyle: '',
    display: '', flexDirection: '', alignItems: '', justifyContent: '', gap: '',
    width: '', height: '', maxWidth: '', minHeight: '', position: '',
    opacity: '', boxShadow: '', transform: '', transition: '', overflow: '',
    zIndex: '', top: '', left: '', right: '', bottom: '',
  });

  const loadSite = () => {
    if (!url.trim()) return;
    setLoadedUrl(url);
  };

  const updateStyle = (prop: string, value: string) => {
    setStyles(prev => ({ ...prev, [prop]: value }));
    // Record change
    if (selectedElement) {
      setChanges(prev => {
        const existing = prev.findIndex(c => c.selector === selectedElement && c.property === prop);
        if (existing >= 0) {
          const updated = [...prev];
          updated[existing] = { ...updated[existing], value };
          return updated;
        }
        return [...prev, { selector: selectedElement, property: prop, value, originalValue: '' }];
      });
    }
  };

  const generateCSS = (): string => {
    const grouped: Record<string, Record<string, string>> = {};
    for (const change of changes) {
      if (!grouped[change.selector]) grouped[change.selector] = {};
      if (change.value) grouped[change.selector][change.property] = change.value;
    }
    let css = '/* Generated by OmniBuilder Style Editor */\n\n';
    for (const [selector, props] of Object.entries(grouped)) {
      const declarations = Object.entries(props)
        .filter(([, v]) => v)
        .map(([k, v]) => `  ${k.replace(/([A-Z])/g, '-$1').toLowerCase()}: ${v};`)
        .join('\n');
      if (declarations) {
        css += `${selector} {\n${declarations}\n}\n\n`;
      }
    }
    return css;
  };

  const exportCSS = () => {
    const css = generateCSS();
    const blob = new Blob([css], { type: 'text/css' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'custom-styles.css';
    a.click();
  };

  const clearChanges = () => {
    if (!confirm('Clear all changes?')) return;
    setChanges([]);
    setStyles(Object.fromEntries(Object.keys(styles).map(k => [k, ''])));
  };

  const renderPropertyGroup = () => {
    switch (activeTab) {
      case 'typography': return (
        <div className="space-y-2">
          <PropInput label="Font Size" prop="fontSize" value={styles.fontSize} onChange={updateStyle} placeholder="16px" />
          <PropSelect label="Font Weight" prop="fontWeight" value={styles.fontWeight} onChange={updateStyle} options={['','100','200','300','400','500','600','700','800','900']} />
          <PropInput label="Font Family" prop="fontFamily" value={styles.fontFamily} onChange={updateStyle} placeholder="Arial, sans-serif" />
          <PropColor label="Color" prop="color" value={styles.color} onChange={updateStyle} />
          <PropSelect label="Text Align" prop="textAlign" value={styles.textAlign} onChange={updateStyle} options={['','left','center','right','justify']} />
          <PropInput label="Line Height" prop="lineHeight" value={styles.lineHeight} onChange={updateStyle} placeholder="1.5" />
          <PropInput label="Letter Spacing" prop="letterSpacing" value={styles.letterSpacing} onChange={updateStyle} placeholder="0px" />
          <PropSelect label="Decoration" prop="textDecoration" value={styles.textDecoration} onChange={updateStyle} options={['','none','underline','line-through','overline']} />
          <PropSelect label="Transform" prop="textTransform" value={styles.textTransform} onChange={updateStyle} options={['','none','uppercase','lowercase','capitalize']} />
        </div>
      );
      case 'spacing': return (
        <div className="space-y-2">
          <PropInput label="Padding" prop="padding" value={styles.padding} onChange={updateStyle} placeholder="0px" />
          <PropInput label="Pad Top" prop="paddingTop" value={styles.paddingTop} onChange={updateStyle} placeholder="0px" />
          <PropInput label="Pad Right" prop="paddingRight" value={styles.paddingRight} onChange={updateStyle} placeholder="0px" />
          <PropInput label="Pad Bottom" prop="paddingBottom" value={styles.paddingBottom} onChange={updateStyle} placeholder="0px" />
          <PropInput label="Pad Left" prop="paddingLeft" value={styles.paddingLeft} onChange={updateStyle} placeholder="0px" />
          <PropInput label="Margin" prop="margin" value={styles.margin} onChange={updateStyle} placeholder="0px" />
          <PropInput label="Mar Top" prop="marginTop" value={styles.marginTop} onChange={updateStyle} placeholder="0px" />
          <PropInput label="Mar Right" prop="marginRight" value={styles.marginRight} onChange={updateStyle} placeholder="0px" />
          <PropInput label="Mar Bottom" prop="marginBottom" value={styles.marginBottom} onChange={updateStyle} placeholder="0px" />
          <PropInput label="Mar Left" prop="marginLeft" value={styles.marginLeft} onChange={updateStyle} placeholder="0px" />
        </div>
      );
      case 'background': return (
        <div className="space-y-2">
          <PropColor label="BG Color" prop="backgroundColor" value={styles.backgroundColor} onChange={updateStyle} />
          <PropInput label="BG Image" prop="backgroundImage" value={styles.backgroundImage} onChange={updateStyle} placeholder="url(...)" />
          <PropSelect label="BG Size" prop="backgroundSize" value={styles.backgroundSize} onChange={updateStyle} options={['','auto','cover','contain']} />
          <PropSelect label="BG Position" prop="backgroundPosition" value={styles.backgroundPosition} onChange={updateStyle} options={['','center','top','bottom','left','right']} />
        </div>
      );
      case 'border': return (
        <div className="space-y-2">
          <PropInput label="Border" prop="border" value={styles.border} onChange={updateStyle} placeholder="1px solid #000" />
          <PropInput label="Radius" prop="borderRadius" value={styles.borderRadius} onChange={updateStyle} placeholder="0px" />
          <PropColor label="Border Color" prop="borderColor" value={styles.borderColor} onChange={updateStyle} />
          <PropInput label="Width" prop="borderWidth" value={styles.borderWidth} onChange={updateStyle} placeholder="1px" />
          <PropSelect label="Style" prop="borderStyle" value={styles.borderStyle} onChange={updateStyle} options={['','none','solid','dashed','dotted','double']} />
        </div>
      );
      case 'layout': return (
        <div className="space-y-2">
          <PropSelect label="Display" prop="display" value={styles.display} onChange={updateStyle} options={['','block','flex','grid','inline','inline-block','none']} />
          <PropSelect label="Flex Dir" prop="flexDirection" value={styles.flexDirection} onChange={updateStyle} options={['','row','column','row-reverse','column-reverse']} />
          <PropSelect label="Align" prop="alignItems" value={styles.alignItems} onChange={updateStyle} options={['','stretch','center','flex-start','flex-end','baseline']} />
          <PropSelect label="Justify" prop="justifyContent" value={styles.justifyContent} onChange={updateStyle} options={['','flex-start','center','flex-end','space-between','space-around','space-evenly']} />
          <PropInput label="Gap" prop="gap" value={styles.gap} onChange={updateStyle} placeholder="0px" />
          <PropInput label="Width" prop="width" value={styles.width} onChange={updateStyle} placeholder="auto" />
          <PropInput label="Height" prop="height" value={styles.height} onChange={updateStyle} placeholder="auto" />
          <PropInput label="Max Width" prop="maxWidth" value={styles.maxWidth} onChange={updateStyle} placeholder="none" />
          <PropSelect label="Position" prop="position" value={styles.position} onChange={updateStyle} options={['','static','relative','absolute','fixed','sticky']} />
          <PropSelect label="Overflow" prop="overflow" value={styles.overflow} onChange={updateStyle} options={['','visible','hidden','scroll','auto']} />
        </div>
      );
      case 'effects': return (
        <div className="space-y-2">
          <PropInput label="Opacity" prop="opacity" value={styles.opacity} onChange={updateStyle} placeholder="1" />
          <PropInput label="Shadow" prop="boxShadow" value={styles.boxShadow} onChange={updateStyle} placeholder="0 2px 4px rgba(0,0,0,0.1)" />
          <PropInput label="Transform" prop="transform" value={styles.transform} onChange={updateStyle} placeholder="none" />
          <PropInput label="Transition" prop="transition" value={styles.transition} onChange={updateStyle} placeholder="all 0.3s ease" />
          <PropInput label="Z-Index" prop="zIndex" value={styles.zIndex} onChange={updateStyle} placeholder="auto" />
        </div>
      );
    }
  };

  return (
    <LayoutShell>
      <div className="h-[calc(100vh-0px)] flex flex-col">
        {/* Top bar */}
        <div className="h-11 bg-white border-b border-gray-200 flex items-center justify-between px-4 shrink-0">
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-purple-600">YellowPencil Mode</span>
            <span className="text-gray-300">|</span>
            <div className="flex items-center gap-1">
              <input value={url} onChange={e => setUrl(e.target.value)} onKeyDown={e => e.key === 'Enter' && loadSite()} placeholder="Enter website URL to edit..." className="h-7 w-72 rounded border border-gray-200 px-2 text-xs focus:border-purple-500 focus:outline-none" />
              <button onClick={loadSite} className="h-7 px-3 rounded bg-purple-600 text-white text-[10px] font-semibold">Load</button>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {(['desktop','tablet','mobile'] as const).map(v => (
              <button key={v} onClick={() => setViewport(v)} className={`h-7 px-2 rounded text-[10px] font-semibold ${viewport === v ? 'bg-purple-600 text-white' : 'bg-gray-100 text-gray-600'}`}>{v[0].toUpperCase()}</button>
            ))}
            <span className="w-px h-4 bg-gray-200" />
            <button onClick={() => setShowCode(!showCode)} className={`h-7 px-2 rounded text-[10px] font-semibold ${showCode ? 'bg-purple-600 text-white' : 'bg-gray-100 text-gray-600'}`}>CSS</button>
            <button onClick={exportCSS} className="h-7 px-2 rounded bg-green-600 text-white text-[10px] font-semibold">Export</button>
            <button onClick={clearChanges} className="h-7 px-2 rounded bg-gray-100 text-[10px] font-semibold text-gray-600">Clear</button>
            <span className="text-[10px] text-gray-400">{changes.length} changes</span>
          </div>
        </div>

        <div className="flex-1 flex overflow-hidden">
          {/* Main content area */}
          <div className="flex-1 bg-gray-100 flex items-center justify-center p-4 overflow-hidden">
            {loadedUrl ? (
              <div className={`bg-white rounded-lg border border-gray-300 shadow-lg overflow-hidden transition-all ${viewport === 'desktop' ? 'w-full h-full' : viewport === 'tablet' ? 'w-[768px] h-full' : 'w-[375px] h-full'}`}>
                <iframe ref={iframeRef} src={loadedUrl} className="w-full h-full border-0" sandbox="allow-same-origin allow-scripts" />
              </div>
            ) : (
              <div className="text-center text-gray-400">
                <div className="w-16 h-16 rounded-full bg-purple-50 flex items-center justify-center mx-auto mb-4"><span className="text-2xl text-purple-400">YP</span></div>
                <p className="text-sm font-medium mb-1">YellowPencil-Style Editor</p>
                <p className="text-xs">Enter a URL above to start editing any website visually</p>
                <p className="text-xs text-gray-300 mt-4">Or use imported pages from the Pages section</p>
              </div>
            )}
          </div>

          {/* Right panel - CSS Editor */}
          <div className="w-[260px] bg-white border-l border-gray-200 flex flex-col overflow-hidden">
            {/* Element info */}
            <div className="p-3 border-b border-gray-100">
              <h4 className="text-[9px] font-bold text-gray-500 uppercase tracking-wider mb-1">Selected Element</h4>
              {selectedElement ? (
                <div>
                  <div className="text-xs font-mono bg-gray-50 px-2 py-1 rounded text-purple-700 mb-1">{selectedElement}</div>
                  <div className="text-[10px] text-gray-400">{elementTag} {elementClasses && `.${elementClasses}`}</div>
                </div>
              ) : (
                <p className="text-[10px] text-gray-400">Click on any element in the preview to select it</p>
              )}
            </div>

            {/* Property tabs */}
            <div className="flex border-b border-gray-100 px-1">
              {(['typography','spacing','background','border','layout','effects'] as const).map(t => (
                <button key={t} onClick={() => setActiveTab(t)} className={`flex-1 py-1.5 text-[8px] font-semibold capitalize ${activeTab === t ? 'text-purple-700 border-b-2 border-purple-600' : 'text-gray-500'}`}>{t.slice(0, 4)}</button>
              ))}
            </div>

            {/* Properties */}
            <div className="flex-1 overflow-y-auto p-3">
              {renderPropertyGroup()}
            </div>

            {/* CSS Output */}
            {showCode && (
              <div className="border-t border-gray-200 h-[200px] overflow-y-auto">
                <div className="p-2">
                  <h4 className="text-[9px] font-bold text-gray-500 uppercase mb-1">Generated CSS</h4>
                  <pre className="text-[9px] font-mono text-green-700 bg-gray-900 text-green-400 p-2 rounded overflow-auto whitespace-pre-wrap">{generateCSS() || '/* No changes yet */'}</pre>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </LayoutShell>
  );
}

// Reusable property input components
function PropInput({ label, prop, value, onChange, placeholder }: { label: string; prop: string; value: string; onChange: (p: string, v: string) => void; placeholder?: string }) {
  return (
    <div>
      <label className="block text-[8px] font-semibold text-gray-500 uppercase">{label}</label>
      <input value={value} onChange={e => onChange(prop, e.target.value)} placeholder={placeholder} className="w-full h-[22px] rounded border border-gray-200 px-1.5 text-[10px] focus:border-purple-500 focus:outline-none" />
    </div>
  );
}

function PropSelect({ label, prop, value, onChange, options }: { label: string; prop: string; value: string; onChange: (p: string, v: string) => void; options: string[] }) {
  return (
    <div>
      <label className="block text-[8px] font-semibold text-gray-500 uppercase">{label}</label>
      <select value={value} onChange={e => onChange(prop, e.target.value)} className="w-full h-[22px] rounded border border-gray-200 px-1 text-[10px] focus:border-purple-500 focus:outline-none">
        {options.map(o => <option key={o} value={o}>{o || '(default)'}</option>)}
      </select>
    </div>
  );
}

function PropColor({ label, prop, value, onChange }: { label: string; prop: string; value: string; onChange: (p: string, v: string) => void }) {
  return (
    <div>
      <label className="block text-[8px] font-semibold text-gray-500 uppercase">{label}</label>
      <div className="flex gap-1">
        <input type="color" value={value || '#000000'} onChange={e => onChange(prop, e.target.value)} className="w-[22px] h-[22px] rounded border-0 cursor-pointer" />
        <input value={value} onChange={e => onChange(prop, e.target.value)} placeholder="#000000" className="flex-1 h-[22px] rounded border border-gray-200 px-1.5 text-[10px] focus:border-purple-500 focus:outline-none" />
      </div>
    </div>
  );
}
